In [42]:
import pandas as pd
df=pd.read_csv("/content/BMW_Car_Sales_Classification.csv")
df

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [43]:
df.head()

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low

In [44]:
df.tail()

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 50000 non-null  object
 1   Year                  50000 non-null  int64
 2   Region                50000 non-null  object
 3   Color                 50000 non-null  object
 4   Fuel_Type             50000 non-null  object
 5   Transmission          50000 non-null  object
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64
 8   Price_USD             50000 non-null  int64
 9   Sales_Volume          50000 non-null  int64
 10  Sales_Classification  50000 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB

In [46]:
df.isnull().sum()

Model                   0
Year                    0
Region                  0
Color                   0
Fuel_Type               0
Transmission            0
Engine_Size_L           0
Mileage_KM              0
Price_USD               0
Sales_Volume            0
Sales_Classification    0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df.describe()

               Year  Engine_Size_L     Mileage_KM      Price_USD  Sales_Volume
count  50000.000000   50000.000000   50000.000000   50000.000000  50000.000000
mean    2017.015700       3.247180  100307.203140   75034.600900   5067.514680
std        4.324459       1.009078   57941.509344   25998.248882   2856.767125
min     2010.000000       1.500000       3.000000   30000.000000    100.000000
25%     2013.000000       2.400000   50178.000000   52434.750000   2588.000000
50%     2017.000000       3.200000  100388.500000   75011.500000   5087.000000
75%     2021.000000       4.100000  150630.250000   97628.250000   7537.250000
max     2024.000000       5.000000  199996.000000  119998.000000   9999.000000

In [49]:
df.shape

(50000, 11)

In [50]:
x=df.iloc[:,:10]
x

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080
...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764

In [51]:
y=df.Sales_Classification
y

0        High
1         Low
2         Low
3         Low
4         Low
         ...
49995    High
49996    High
49997    High
49998    High
49999     Low
Name: Sales_Classification, Length: 50000, dtype: object

In [52]:
x = pd.get_dummies(x, drop_first=True, dtype=int)
x

,Year,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Model_5 Series,Model_7 Series,Model_M3,Model_M5,Model_X1,...,Region_South America,Color_Blue,Color_Grey,Color_Red,Color_Silver,Color_White,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Manual
0,2016,3.5,151748,98740,8300,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,1
1,2013,1.6,121671,79219,3428,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,2022,4.5,10991,113265,6994,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,2024,1.7,27255,60971,4047,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,2020,2.1,122131,49898,3080,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2014,4.6,151030,42932,8182,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
49996,2023,4.2,147396,48714,9816,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,1
49997,2010,4.5,174939,46126,8280,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
49998,2020,3.8,3379,58566,9486,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
49999,2020,3.3,171003,77492,1764,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y = le.fit_transform(y)
y

array([0, 1, 1, ..., 0, 0, 1])

In [54]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=41)

In [55]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtrain

array([[-0.23468581,  1.6347057 , -0.32258081, ..., -0.58258502,
         1.73310718,  0.99708995],
       [ 1.15410504,  0.64520008,  0.57113456, ...,  1.71648767,
        -0.57699836, -1.00291854],
       [-1.16054638, -0.64115724,  1.57350446, ..., -0.58258502,
        -0.57699836,  0.99708995],
       ...,
       [ 0.45970961, -1.43276174, -1.14836553, ..., -0.58258502,
         1.73310718, -1.00291854],
       [-0.92908124,  0.54624951,  0.13541163, ..., -0.58258502,
        -0.57699836, -1.00291854],
       [-1.62347666,  0.15044726, -1.29001001, ..., -0.58258502,
         1.73310718, -1.00291854]])

In [56]:
xtest = scaler.transform(xtest)
xtest

array([[-0.23468581,  0.0514967 , -0.77354714, ...,  1.71648767,
        -0.57699836, -1.00291854],
       [ 0.92263989,  0.15044726,  0.57336152, ..., -0.58258502,
         1.73310718, -1.00291854],
       [ 0.22824447, -0.83905836, -0.20803954, ..., -0.58258502,
        -0.57699836,  0.99708995],
       ...,
       [-0.00322067, -0.44325611, -0.71402366, ..., -0.58258502,
        -0.57699836, -1.00291854],
       [-1.16054638, -1.33381118, -0.97146962, ..., -0.58258502,
         1.73310718, -1.00291854],
       [-1.16054638,  0.94205176, -1.40983382, ...,  1.71648767,
        -0.57699836,  0.99708995]])

In [63]:
pd.Series(ytrain).value_counts()

1    24409
0    10591
Name: count, dtype: int64

In [58]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()
xtrain1, ytrain1 = sm.fit_resample(xtrain, ytrain)

In [61]:
pd.Series(ytrain1).value_counts()

1    24409
0    24409
Name: count, dtype: int64

In [64]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
model=knn.fit(xtrain1,ytrain1)
model

KNeighborsClassifier(n_neighbors=7)

In [65]:
ypred=knn.predict(xtest)
ypred

array([1, 1, 1, ..., 1, 1, 0])

In [69]:
ytest

array([1, 0, 1, ..., 1, 1, 0])

In [70]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(ytest, ypred)
acc

0.7819333333333334