# ENCODING:

#### **Encoding** → The process of converting **categorical (text) data into numerical data** so that a Machine Learning model can understand and use it.

### 3 MAIN TYPES

#### 1) LABEL ENCODING
- Assigns a **number to each category**.
- Example: `Male → 0`, `Female → 1`

#### 2) ONE-HOT ENCODING
- Converts each category into a **separate column**.
- Uses **0 and 1** to represent the categories.

#### 3) GET DUMMIES
- `get_dummies()` is a **Pandas function** used to perform **One-Hot Encoding**.
- It automatically creates separate columns for each category.

---

### TYPES OF CATEGORICAL DATA

**Nominal Data** → Categories have **no natural order**.  
Example: `Red, Blue, Green`

**Ordinal Data** → Categories have a **meaningful order**.  
Example: `Low < Medium < High`

### 1) LABEL ENCODING  

FRUITS:

APPLE-0

BANANA-1

CHERRY-2

GRAPES-3

APPLE-0

Label Encoding is generally more suitable when the categories have a natural order (ordinal data).


---
### 2) ONE HOT ENCODING

*APPLE | BANANA | CHERRY | GRAPES*

| APPLE | BANANA | CHERRY | GRAPES |
|---|---|---|---|
| T | F | F | F |
| F | T | F | F |
| F | F | T | F |
| F | F | F | T |

**1 COL → 4 COL**

---

### 3) GET DUMMIES

**BANANA | CHERRY | GRAPES**

| BANANA | CHERRY | GRAPES |
|---|---|---|
| F | F | F |
| T | F | F |
| F | T | F |
| F | F | T |

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/weatherData (1).csv",header=None,names=["Outlook","Temperature","Humidity","Wind","Play"])
df

     Outlook Temperature Humidity   Wind Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     bool
 4   Play         14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes

In [ ]:
df.describe()

       Outlook Temperature Humidity   Wind Play
count       14          14       14     14   14
unique       3           3        2      2    2
top      sunny        mild     high  False  yes
freq         5           6        7      8    9

In [ ]:
df["Outlook"].values

array(['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy',
       'overcast', 'sunny', 'sunny', 'rainy', 'sunny', 'overcast',
       'overcast', 'rainy'], dtype=object)

In [ ]:
# Creating a Label Encoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
## Applying Label Encoding to a Column
---------------------------------------
# outlook
# df["Outlook"]=le.fit_transform(df["Outlook"])
# means:Select the Outlook column → learn its categories → convert them into numbers → replace the original text values with those numbers.

In [ ]:
df["Outlook"].values

array(['sunny', 'sunny', 'overcast', 'rainy', 'rainy', 'rainy',
       'overcast', 'sunny', 'sunny', 'rainy', 'sunny', 'overcast',
       'overcast', 'rainy'], dtype=object)

In [ ]:
# sunny | overcast | rainy
#  2        0         1

In [ ]:
# Temperature
# df["Temperature"]=le.fit_transform(df["Temperature"])

In [ ]:
df["Temperature"].values

array(['hot', 'hot', 'hot', 'mild', 'cool', 'cool', 'cool', 'mild',
       'cool', 'mild', 'mild', 'mild', 'hot', 'mild'], dtype=object)

In [ ]:
# hot | mild | cool
#  1      2     0

In [ ]:
# Humidity
# df["Humidity"]=le.fit_transform(df["Humidity"])

In [ ]:
df["Humidity"].values

array(['high', 'high', 'high', 'high', 'normal', 'normal', 'normal',
       'high', 'normal', 'normal', 'normal', 'high', 'normal', 'high'],
      dtype=object)

In [ ]:
# High | Normal
#  0       1

In [ ]:
# Wind
# df["Wind"]=le.fit_transform(df["Wind"])

In [ ]:
df["Wind"].values

array([False,  True, False, False, False,  True,  True, False, False,
       False,  True,  True, False,  True])

In [ ]:
# false | true
#   0      1

In [ ]:
df

     Outlook Temperature Humidity   Wind Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
# Label Encoding All Columns Using a for Loop
for i in df.columns:
df[i]=le.fit_transform(df[i])
  # Meaning:
     # df[i] → selects the current column.
     # le.fit_transform(df[i]) → learns the categories and converts them into numbers.
     # df[i] = → puts the encoded values back into that same column.

df

    Outlook  Temperature  Humidity  Wind  Play
0         2            1         0     0     0
1         2            1         0     1     0
2         0            1         0     0     1
3         1            2         0     0     1
4         1            0         1     0     1
5         1            0         1     1     0
6         0            0         1     1     1
7         2            2         0     0     0
8         2            0         1     0     1
9         1            2         1     0     1
10        2            2         1     1     1
11        0            2         0     1     1
12        0            1         1     0     1
13        1            2         0     1     0