In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/weatherData (1).csv",
               header=None,
               names=["Outlook","Temperature","Humidity","Wind","Play"])
df

     Outlook Temperature Humidity   Wind Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
## Outlook
# Encode 'Outlook' Column
le_o=LabelEncoder()
le1=le_o.fit(df["Outlook"])
df["Outlook"]=le1.transform(df["Outlook"])
df

    Outlook Temperature Humidity   Wind Play
0         2         hot     high  False   no
1         2         hot     high   True   no
2         0         hot     high  False  yes
3         1        mild     high  False  yes
4         1        cool   normal  False  yes
5         1        cool   normal   True   no
6         0        cool   normal   True  yes
7         2        mild     high  False   no
8         2        cool   normal  False  yes
9         1        mild   normal  False  yes
10        2        mild   normal   True  yes
11        0        mild     high   True  yes
12        0         hot   normal  False  yes
13        1        mild     high   True   no

In [ ]:
# View Original Labels for Outlook
le1.inverse_transform([0,1,2])

array(['overcast', 'rainy', 'sunny'], dtype=object)

In [ ]:
# Temperature
le_t=LabelEncoder()
le2=le_o.fit(df["Temperature"])
df["Temperature"]=le2.transform(df["Temperature"])
df

    Outlook  Temperature Humidity   Wind Play
0         2            1     high  False   no
1         2            1     high   True   no
2         0            1     high  False  yes
3         1            2     high  False  yes
4         1            0   normal  False  yes
5         1            0   normal   True   no
6         0            0   normal   True  yes
7         2            2     high  False   no
8         2            0   normal  False  yes
9         1            2   normal  False  yes
10        2            2   normal   True  yes
11        0            2     high   True  yes
12        0            1   normal  False  yes
13        1            2     high   True   no

In [ ]:
le2.inverse_transform([0,1,2])

array(['cool', 'hot', 'mild'], dtype=object)

In [ ]:
# Humidity
le_h=LabelEncoder()
le3=le_o.fit(df["Humidity"])
df["Humidity"]=le3.transform(df["Humidity"])
df

    Outlook  Temperature  Humidity   Wind Play
0         2            1         0  False   no
1         2            1         0   True   no
2         0            1         0  False  yes
3         1            2         0  False  yes
4         1            0         1  False  yes
5         1            0         1   True   no
6         0            0         1   True  yes
7         2            2         0  False   no
8         2            0         1  False  yes
9         1            2         1  False  yes
10        2            2         1   True  yes
11        0            2         0   True  yes
12        0            1         1  False  yes
13        1            2         0   True   no

In [ ]:
le3.inverse_transform([0,1])

array(['high', 'normal'], dtype=object)

In [ ]:
# Wind
le_w=LabelEncoder()
le4=le_o.fit(df["Wind"])
df["Wind"]=le4.transform(df["Wind"])
df

    Outlook  Temperature  Humidity  Wind Play
0         2            1         0     0   no
1         2            1         0     1   no
2         0            1         0     0  yes
3         1            2         0     0  yes
4         1            0         1     0  yes
5         1            0         1     1   no
6         0            0         1     1  yes
7         2            2         0     0   no
8         2            0         1     0  yes
9         1            2         1     0  yes
10        2            2         1     1  yes
11        0            2         0     1  yes
12        0            1         1     0  yes
13        1            2         0     1   no

In [ ]:
le4.inverse_transform([0,1])

array([False,  True])

In [ ]:
x=df.iloc[:,:4]
x

    Outlook  Temperature  Humidity  Wind
0         2            1         0     0
1         2            1         0     1
2         0            1         0     0
3         1            2         0     0
4         1            0         1     0
5         1            0         1     1
6         0            0         1     1
7         2            2         0     0
8         2            0         1     0
9         1            2         1     0
10        2            2         1     1
11        0            2         0     1
12        0            1         1     0
13        1            2         0     1

In [ ]:
y=df.Play
y

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: Play, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=41)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(xtrain,ytrain)

MultinomialNB()

In [ ]:
ypred=mnb.predict(xtest)
ypred

array(['no', 'no', 'yes', 'no', 'no'], dtype='<U3')

In [ ]:
y_new=mnb.predict([[
    le1.transform(["sunny"]).item(0),
    le2.transform(["cool"]).item(0),
    le3.transform(["high"]).item(0),
    le4.transform(["True"]).item(0)]])
y_new

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array(['no'], dtype='<U3')