## --- PANDAS ---
### Used for:
### . data manipulation
### . data cleaning
### . data analysis
### . data transportation
### . structured data/tabular data

In [1]:
 #! pip install pandas

In [2]:
 #! Pandas mainly has 2 data structures:
# ---------------
#! 1) Series → 1-dimensional data (like a single column)
#! 2) DataFrame → 2-dimensional data (like a table with rows and columns)

In [3]:
import pandas as pd

## Series: 1-dimensional data (like a single column)

In [ ]:
 #! Series: 
  #! Here we will get the 1st column as indexes and 2nd column as the values
# -------------
marks=pd.Series([23,25,23,29,30,27,23])
marks

0    23
1    25
2    23
3    29
4    30
5    27
6    23
dtype: int64

In [5]:
 #? Indexing:
marks[0]

np.int64(23)

In [ ]:
 #! Custom Indexing
# -------------
marks1=pd.Series([29,33,34,36],index=["A","B","C","D"])    #* Data can have meaningfull labels
marks1

A    29
B    33
C    34
D    36
dtype: int64

In [7]:
marks1["A"]

np.int64(29)

In [8]:
 #! Series from dictionary
# ------------
dict={"Anu":25,"Adhi":30,"Anjali":28}
marks2=pd.Series(dict)
marks2

Anu       25
Adhi      30
Anjali    28
dtype: int64

## Series Properties

In [9]:
marks2.index   #* returns index labels

Index(['Anu', 'Adhi', 'Anjali'], dtype='str')

In [10]:
marks2.values   #* returns values

array([25, 30, 28])

In [11]:
marks2.dtype

dtype('int64')

In [12]:
marks2.ndim

1

In [13]:
marks2.shape

(3,)

In [14]:
marks2.size

3

## Series Methods

In [15]:
marks

0    23
1    25
2    23
3    29
4    30
5    27
6    23
dtype: int64

In [ ]:
 #! head() :returns the first 5 rows by default
marks.head(3)

0    23
1    25
2    23
dtype: int64

In [17]:
 #! tail(): returns the last 5 rows by default
marks.tail(2)

5    27
6    23
dtype: int64

In [18]:
marks.sum()

np.int64(180)

In [19]:
marks.mean()

np.float64(25.714285714285715)

In [20]:
marks.max()

np.int64(30)

In [21]:
marks.min()

np.int64(23)

In [22]:
 #! count -> Returns the non null value count
marks.count()

np.int64(7)

## DataFrame: 2 D labeled data structures consisting of rows and columns

In [23]:
data={
    "name":["Anu","Rahul","meera","Akhil","Arun"],
    "age":[19,22,24,20,25],
    "marks":[85,90,92,79,91],
    "loc":["calicut","kochi","kochi","calicut","wayanad"]
    }

In [24]:
df=pd.DataFrame(data,index=["S1","S2","S3","S4","S5"])
df

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi
S4  Akhil   20     79  calicut
S5   Arun   25     91  wayanad

In [25]:
 #! Indexing
df["name"]

S1      Anu
S2    Rahul
S3    meera
S4    Akhil
S5     Arun
Name: name, dtype: str

### DataFrame Properties

In [26]:
df.shape

(5, 4)

In [27]:
df.size

20

In [28]:
df.ndim

2

In [29]:
df.columns

Index(['name', 'age', 'marks', 'loc'], dtype='str')

In [30]:
df.index

Index(['S1', 'S2', 'S3', 'S4', 'S5'], dtype='str')

In [31]:
df.dtypes

name       str
age      int64
marks    int64
loc        str
dtype: object

### DataFrame Methods

In [32]:
df.head()

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi
S4  Akhil   20     79  calicut
S5   Arun   25     91  wayanad

In [33]:
df.head(3)

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi

In [34]:
df.tail()

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi
S4  Akhil   20     79  calicut
S5   Arun   25     91  wayanad

In [35]:
df.tail(3)

     name  age  marks      loc
S3  meera   24     92    kochi
S4  Akhil   20     79  calicut
S5   Arun   25     91  wayanad

In [36]:
 #! info -> Is used to get summary information about a DataFrame.
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, S1 to S5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
 3   loc     5 non-null      str
dtypes: int64(2), str(2)
memory usage: 435.0 bytes

<!-- DataFrame Properties -->

In [37]:
 #! describe() -> Is used to get the statistical summary of numerical columns in DataFrame
df.describe()

            age      marks
count   5.00000   5.000000
mean   22.00000  87.400000
std     2.54951   5.412947
min    19.00000  79.000000
25%    20.00000  85.000000
50%    22.00000  90.000000
75%    24.00000  91.000000
max    25.00000  92.000000

In [ ]:
 #! describe(include="all") -> Give a summary of all columns in the DataFrame, including both numerical and non-numerical columns.
df.describe(include="all")

       name       age      marks      loc
count     5   5.00000   5.000000        5
unique    5       NaN        NaN        3
top     Anu       NaN        NaN  calicut
freq      1       NaN        NaN        2
mean    NaN  22.00000  87.400000      NaN
std     NaN   2.54951   5.412947      NaN
min     NaN  19.00000  79.000000      NaN
25%     NaN  20.00000  85.000000      NaN
50%     NaN  22.00000  90.000000      NaN
75%     NaN  24.00000  91.000000      NaN
max     NaN  25.00000  92.000000      NaN

In [39]:
 #! Selecting a column 
df["name"]
#* o/p=> Series

S1      Anu
S2    Rahul
S3    meera
S4    Akhil
S5     Arun
Name: name, dtype: str

In [40]:
 #! Selecting multiple columns
df[["name","loc"]]
#* o/p=> Dataframe

     name      loc
S1    Anu  calicut
S2  Rahul    kochi
S3  meera    kochi
S4  Akhil  calicut
S5   Arun  wayanad

In [ ]:
 #! Selecting rows
#! 1)loc : used for label based indexing
df.loc["S1"]

name         Anu
age           19
marks         85
loc      calicut
Name: S1, dtype: object

In [42]:
df.loc["S1":"S4"]

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi
S4  Akhil   20     79  calicut

In [ ]:
 #! 2)iloc -> integer location based indexing
df.iloc[0]

name         Anu
age           19
marks         85
loc      calicut
Name: S1, dtype: object

In [44]:
df.iloc[0:2]     # from 0 to 2-1

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi

In [45]:
 #! retrieving the value in S1 row and Name column
df.loc["S1","name"]

'Anu'

In [46]:
df.iloc[0,0]

'Anu'

In [74]:
 #! filtering Data
#? marks>90 ?
# df[condition]
df[df["marks"]>90]  # df is used inside coz if not used it just shows true or false

    name  age  marks      loc Grade
1  meera   24     94    KOCHI     A
3   Arun   25     93  WAYANAD     A

In [48]:
 #? marks>90 and age>20 ?
df[(df["marks"]>90) & (df["age"]>20)]

     name  age  marks      loc
S3  meera   24     92    kochi
S5   Arun   25     91  wayanad

In [49]:
 #? either marks>90 or age>20 ?
df[(df["marks"]>90) | (df["age"]>20)]

     name  age  marks      loc
S2  Rahul   22     90    kochi
S3  meera   24     92    kochi
S5   Arun   25     91  wayanad

In [50]:
 #? Exclude marks>90 ?
df[~(df["marks"]>90)]

     name  age  marks      loc
S1    Anu   19     85  calicut
S2  Rahul   22     90    kochi
S4  Akhil   20     79  calicut

In [51]:
 #! Adding New Column
df["Grade"]=["B","A","A","","A"]
df

     name  age  marks      loc Grade
S1    Anu   19     85  calicut     B
S2  Rahul   22     90    kochi     A
S3  meera   24     92    kochi     A
S4  Akhil   20     79  calicut
S5   Arun   25     91  wayanad     A

In [52]:
 #! Creating new column from an existing column
df["new marks"]=df["marks"]*2
df

     name  age  marks      loc Grade  new marks
S1    Anu   19     85  calicut     B        170
S2  Rahul   22     90    kochi     A        180
S3  meera   24     92    kochi     A        184
S4  Akhil   20     79  calicut              158
S5   Arun   25     91  wayanad     A        182

In [53]:
 #! Modifying A column
df["marks"]=df["marks"]+2
df

     name  age  marks      loc Grade  new marks
S1    Anu   19     87  calicut     B        170
S2  Rahul   22     92    kochi     A        180
S3  meera   24     94    kochi     A        184
S4  Akhil   20     81  calicut              158
S5   Arun   25     93  wayanad     A        182

In [54]:
df["loc"]=df["loc"].str.upper()
df

     name  age  marks      loc Grade  new marks
S1    Anu   19     87  CALICUT     B        170
S2  Rahul   22     92    KOCHI     A        180
S3  meera   24     94    KOCHI     A        184
S4  Akhil   20     81  CALICUT              158
S5   Arun   25     93  WAYANAD     A        182

In [55]:
 #! Deleting columns
#! drop() 
df.drop("new marks",axis=1)   # deletes temporarily
# df=df.drop("new marks",axis=1)

     name  age  marks      loc Grade
S1    Anu   19     87  CALICUT     B
S2  Rahul   22     92    KOCHI     A
S3  meera   24     94    KOCHI     A
S4  Akhil   20     81  CALICUT
S5   Arun   25     93  WAYANAD     A

In [ ]:
 #! inplace: retrieve dropped column
df.drop("new marks",axis=1,inplace=True)

In [57]:
df

     name  age  marks      loc Grade
S1    Anu   19     87  CALICUT     B
S2  Rahul   22     92    KOCHI     A
S3  meera   24     94    KOCHI     A
S4  Akhil   20     81  CALICUT
S5   Arun   25     93  WAYANAD     A

In [58]:
df.drop("S2",inplace=True)

In [59]:
df

     name  age  marks      loc Grade
S1    Anu   19     87  CALICUT     B
S3  meera   24     94    KOCHI     A
S4  Akhil   20     81  CALICUT
S5   Arun   25     93  WAYANAD     A

In [60]:
 #! reset_index -> Used to reset the index of a DataFrame back to the default numbers (0, 1, 2, 3, …)
df=df.reset_index(drop=True)

In [61]:
df

    name  age  marks      loc Grade
0    Anu   19     87  CALICUT     B
1  meera   24     94    KOCHI     A
2  Akhil   20     81  CALICUT
3   Arun   25     93  WAYANAD     A

In [62]:
 #! adding new rows
new={"name":"Anumol",
     "age":19,
     "marks":85,
     "loc":"calicut",
     "Grade":"B"
     }
new_df=pd.DataFrame(new,index=["S6"])

In [ ]:
 #! concat() -> Used to combine two or more Pandas DataFrames or Series.
#! ignore_index=True → resets the index numbers after combining
df=pd.concat([df,new_df],ignore_index=True)

In [64]:
df

     name  age  marks      loc Grade
0     Anu   19     87  CALICUT     B
1   meera   24     94    KOCHI     A
2   Akhil   20     81  CALICUT
3    Arun   25     93  WAYANAD     A
4  Anumol   19     85  calicut     B

In [65]:
import pandas as pd
dt={"name":["rajesh","arun","manoj","adhil","rohini"],
    "age":[26,29,28,26,25],
    "department":["IT","Finance","HR","IT","HR"],
    "salary":[28000,35000,32000,30000,25000]}
df3=pd.DataFrame(dt)
df3

     name  age department  salary
0  rajesh   26         IT   28000
1    arun   29    Finance   35000
2   manoj   28         HR   32000
3   adhil   26         IT   30000
4  rohini   25         HR   25000

In [66]:
 #! unique(): Used to find the unique value in a column
df3["department"].unique()

<ArrowStringArray>
['IT', 'Finance', 'HR']
Length: 3, dtype: str

In [67]:
 #! nunique(): Returns the no.of unique value
df3["department"].nunique()

3

In [68]:
 #! value_counts() -> Used to count how many times each unique value occurs in a Series/column
df3["department"].value_counts()

department
IT         2
HR         2
Finance    1
Name: count, dtype: int64

In [69]:
 #! sum()
df3["salary"].sum()

np.int64(150000)

In [70]:
 #! mean()
df3["salary"].mean()

np.float64(30000.0)

In [71]:
 #! max()
df3["salary"].max()

 #! min()
df3["salary"].min()

np.int64(25000)

In [72]:
 #! var()
df3["salary"].var()

np.float64(14500000.0)