In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\Data Science\EDA\nongraphical\sales_eda_dataset.csv")
df

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
0,1001,2025-03-13,Mobile,Electronics,Kochi,3,5,31049,5.0,147482.75,Anu
1,1002,2025-04-22,Mobile,Electronics,Bangalore,1,1,16952,0.0,16952.00,Meera
2,1003,2025-10-29,Laptop,Electronics,Trivandrum,2,7,59446,15.0,353703.70,Anu
3,1004,2025-04-21,Tablet,Electronics,Bangalore,2,6,21105,5.0,120298.50,Anu
4,1005,2025-11-06,Mobile,Electronics,Bangalore,2,2,38526,10.0,69346.80,Anu
...,...,...,...,...,...,...,...,...,...,...,...
148,1149,2025-05-01,Laptop,Electronics,Kollam,2,4,74057,15.0,251793.80,Anu
149,1150,2025-04-08,Mouse,Accessories,Kollam,1,1,2130,10.0,1917.00,Arun
150,1011,2025-05-18,Laptop,Electronics,Trivandrum,1,1,65673,15.0,55822.05,Rahul
151,1036,2025-10-24,Headphones,Accessories,Bangalore,3,2,5666,5.0,10765.40,Anu
152,1081,2025-01-14,Mobile,Electronics,Kannur,2,5,22084,20.0,88336.00,Meera

In [3]:
df.shape

(153, 11)

In [4]:
 #! columns -> Is used to view or work with the column names of a DataFrame.
df.columns

Index(['Order_ID', 'Order_Date', 'Product', 'Category', 'City', 'Region_ID',
       'Quantity', 'Unit_Price', 'Discount_Percent', 'Sales', 'Salesperson'],
      dtype='str')

In [5]:
df.dtypes

Order_ID              int64
Order_Date              str
Product                 str
Category                str
City                    str
Region_ID             int64
Quantity              int64
Unit_Price            int64
Discount_Percent    float64
Sales               float64
Salesperson             str
dtype: object

In [6]:
 #! info() -> gives you a summary of the DataFrame.
df.info

<bound method DataFrame.info of      Order_ID  Order_Date     Product     Category        City  Region_ID  \
0        1001  2025-03-13      Mobile  Electronics       Kochi          3
1        1002  2025-04-22      Mobile  Electronics   Bangalore          1
2        1003  2025-10-29      Laptop  Electronics  Trivandrum          2
3        1004  2025-04-21      Tablet  Electronics   Bangalore          2
4        1005  2025-11-06      Mobile  Electronics   Bangalore          2
..        ...         ...         ...          ...         ...        ...
148      1149  2025-05-01      Laptop  Electronics      Kollam          2
149      1150  2025-04-08       Mouse  Accessories      Kollam          1
150      1011  2025-05-18      Laptop  Electronics  Trivandrum          1
151      1036  2025-10-24  Headphones  Accessories   Bangalore          3
152      1081  2025-01-14      Mobile  Electronics      Kannur          2

     Quantity  Unit_Price  Discount_Percent      Sales Salesperson
0           5       31049               5.0  147482.75         Anu
1           1       16952               0.0   16952.00       Meera
2           7       59446              15.0  353703.70         Anu
3           6       21105               5.0  120298.50         Anu
4           2       38526              10.0   69346.80         Anu
..        ...         ...               ...        ...         ...
148         4       74057              15.0  251793.80         Anu
149         1        2130              10.0    1917.00        Arun
150         1       65673              15.0   55822.05       Rahul
151         2        5666               5.0   10765.40         Anu
152         5       22084              20.0   88336.00       Meera

[153 rows x 11 columns]>

In [7]:
 #! describe() -> gives you a statistical summary of the numerical columns in a DataFrame.
#? To include categorical/text columns:
df.describe(include="all")

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
count,153.000000,153,153,153,150,153.000000,153.000000,153.000000,149.000000,153.000000,150
unique,NaN,133,8,2,8,NaN,NaN,NaN,NaN,NaN,6
top,NaN,2025-05-23,Headphones,Electronics,Chennai,NaN,NaN,NaN,NaN,NaN,Rahul
freq,NaN,3,24,93,34,NaN,NaN,NaN,NaN,NaN,34
mean,1074.856209,NaN,NaN,NaN,NaN,2.013072,4.313725,21660.797386,10.838926,83636.927451,NaN
std,43.447248,NaN,NaN,NaN,NaN,0.811001,2.246256,22190.192085,6.560598,108848.807246,NaN
min,1001.000000,NaN,NaN,NaN,NaN,1.000000,1.000000,551.000000,0.000000,862.200000,NaN
25%,1037.000000,NaN,NaN,NaN,NaN,1.000000,2.000000,3584.000000,5.000000,10765.400000,NaN
50%,1075.000000,NaN,NaN,NaN,NaN,2.000000,4.000000,14451.000000,10.000000,36850.050000,NaN
75%,1112.000000,NaN,NaN,NaN,NaN,3.000000,6.000000,30155.000000,15.000000,118101.600000,NaN
max,1150.000000,NaN,NaN,NaN,NaN,3.000000,8.000000,83916.000000,20.000000,570628.800000,NaN

In [8]:
df.describe(include="object")

C:\Users\adhil\AppData\Local\Temp\ipykernel_19400\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

        Order_Date     Product     Category     City Salesperson
count          153         153          153      150         150
unique         133           8            2        8           6
top     2025-05-23  Headphones  Electronics  Chennai       Rahul
freq             3          24           93       34          34

In [9]:
 #! unique -> Is used to find the different/distinct values in a column.
df["Product"].unique()

<ArrowStringArray>
[    'Mobile',     'Laptop',     'Tablet', 'Smartwatch',      'Mouse',
 'Headphones',    'Monitor',   'Keyboard']
Length: 8, dtype: str

In [10]:
df["Category"].unique()

<ArrowStringArray>
['Electronics', 'Accessories']
Length: 2, dtype: str

In [11]:
df["City"].unique

<bound method Series.unique of 0           Kochi
1       Bangalore
2      Trivandrum
3       Bangalore
4       Bangalore
          ...
148        Kollam
149        Kollam
150    Trivandrum
151     Bangalore
152        Kannur
Name: City, Length: 153, dtype: str>

In [12]:
 #! value_counts() -> Is used to find how many times each unique value appears in a column.
df["Category"].value_counts()

Category
Electronics    93
Accessories    60
Name: count, dtype: int64

In [13]:
df["Salesperson"].value_counts()

Salesperson
Rahul     34
Jiya      28
Meera     24
Anu       22
Vishnu    21
Arun      21
Name: count, dtype: int64

In [14]:
# total sales
df["Sales"].sum()

np.float64(12796449.9)

In [15]:
# average sales
df["Sales"].mean()

np.float64(83636.9274509804)

In [16]:
df["Sales"].max()

np.float64(570628.8)

In [17]:
df["Sales"].min()

np.float64(862.2)

In [18]:
# total quantity sold
df["Quantity"].sum()

np.int64(660)

In [19]:
df["Discount_Percent"].mean()

np.float64(10.838926174496644)

## DATA CLEANING

In [20]:
 #! Handling Null Values
# ---------
 #! isnull() or isna() : Returns true if null
df.isnull()

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
148,False,False,False,False,False,False,False,False,False,False,False
149,False,False,False,False,False,False,False,False,False,False,False
150,False,False,False,False,False,False,False,False,False,False,False
151,False,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,False

In [21]:
 #! column wise null value count
df.isnull().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                3
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    4
Sales               0
Salesperson         3
dtype: int64

In [22]:
 #! column wise percentage of null value
df.isnull().mean()*100

Order_ID            0.000000
Order_Date          0.000000
Product             0.000000
Category            0.000000
City                1.960784
Region_ID           0.000000
Quantity            0.000000
Unit_Price          0.000000
Discount_Percent    2.614379
Sales               0.000000
Salesperson         1.960784
dtype: float64

In [23]:
 #! total null value count
df.isnull().sum().sum()

np.int64(10)

In [24]:
df["City"].isnull().sum()

np.int64(3)

In [25]:
df[df["City"].isnull()]

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
5,1006,2025-05-31,Smartwatch,Electronics,NaN,3,7,5582,20.0,31259.2,Meera
23,1024,2025-04-28,Headphones,Accessories,NaN,1,1,1581,0.0,1581.0,Anu
54,1055,2025-11-16,Headphones,Accessories,NaN,2,7,1573,10.0,9909.9,Vishnu

In [26]:
df[df["Salesperson"].isnull()]

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
17,1018,2025-10-04,Keyboard,Accessories,Trivandrum,3,3,3863,5.0,11009.55,NaN
52,1053,2025-06-10,Keyboard,Accessories,Kochi,2,2,4359,10.0,7846.20,NaN
144,1145,2025-11-29,Mouse,Accessories,Trivandrum,2,2,2401,10.0,4321.80,NaN

In [27]:
 #! finding the most frequently occurring city in the City column.
mode_city=df["City"].mode()[0]
mode_city

'Chennai'

In [28]:
 #! fillna() -> Is used to replace missing values (NaN) in a DataFrame or Series.
df["City"]=df["City"].fillna(mode_city)

In [29]:
df.isna().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                0
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    4
Sales               0
Salesperson         3
dtype: int64

In [ ]:
df["Salesperson"]=df["Salesperson"].fillna(df["Salesperson"].mode()[0])
#? It is a categorical column, not a numerical column.
#? [0] means take the first value.

In [31]:
df.isna().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                0
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    4
Sales               0
Salesperson         0
dtype: int64

In [32]:
df["Discount_Percent"]=df["Discount_Percent"].fillna(df["Discount_Percent"].median())
#? Median,Because Discount_Percent is numerical data, and the median is safer when there may be outliers.

In [33]:
df.isna().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                0
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Salesperson         0
dtype: int64

In [34]:
 #! ffill() -> It is used to fill missing (NaN) values using the previous available value (forward fill)
df.head()

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
0,1001,2025-03-13,Mobile,Electronics,Kochi,3,5,31049,5.0,147482.75,Anu
1,1002,2025-04-22,Mobile,Electronics,Bangalore,1,1,16952,0.0,16952.00,Meera
2,1003,2025-10-29,Laptop,Electronics,Trivandrum,2,7,59446,15.0,353703.70,Anu
3,1004,2025-04-21,Tablet,Electronics,Bangalore,2,6,21105,5.0,120298.50,Anu
4,1005,2025-11-06,Mobile,Electronics,Bangalore,2,2,38526,10.0,69346.80,Anu

In [35]:
df.isna().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                0
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Salesperson         0
dtype: int64

In [36]:
 #! bfill() -> It fills missing (NaN) values using the next available value.
df["Salesperson"]=df["Salesperson"].bfill()

In [37]:
df.isna().sum()

Order_ID            0
Order_Date          0
Product             0
Category            0
City                0
Region_ID           0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Salesperson         0
dtype: int64

In [38]:
 #! dropna() -> Deletes rows having null value
df.dropna()   #axis=0-default

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
0,1001,2025-03-13,Mobile,Electronics,Kochi,3,5,31049,5.0,147482.75,Anu
1,1002,2025-04-22,Mobile,Electronics,Bangalore,1,1,16952,0.0,16952.00,Meera
2,1003,2025-10-29,Laptop,Electronics,Trivandrum,2,7,59446,15.0,353703.70,Anu
3,1004,2025-04-21,Tablet,Electronics,Bangalore,2,6,21105,5.0,120298.50,Anu
4,1005,2025-11-06,Mobile,Electronics,Bangalore,2,2,38526,10.0,69346.80,Anu
...,...,...,...,...,...,...,...,...,...,...,...
148,1149,2025-05-01,Laptop,Electronics,Kollam,2,4,74057,15.0,251793.80,Anu
149,1150,2025-04-08,Mouse,Accessories,Kollam,1,1,2130,10.0,1917.00,Arun
150,1011,2025-05-18,Laptop,Electronics,Trivandrum,1,1,65673,15.0,55822.05,Rahul
151,1036,2025-10-24,Headphones,Accessories,Bangalore,3,2,5666,5.0,10765.40,Anu
152,1081,2025-01-14,Mobile,Electronics,Kannur,2,5,22084,20.0,88336.00,Meera

In [39]:
df.dropna(axis=1)  #column

,Order_ID,Order_Date,Product,Category,City,Region_ID,Quantity,Unit_Price,Discount_Percent,Sales,Salesperson
0,1001,2025-03-13,Mobile,Electronics,Kochi,3,5,31049,5.0,147482.75,Anu
1,1002,2025-04-22,Mobile,Electronics,Bangalore,1,1,16952,0.0,16952.00,Meera
2,1003,2025-10-29,Laptop,Electronics,Trivandrum,2,7,59446,15.0,353703.70,Anu
3,1004,2025-04-21,Tablet,Electronics,Bangalore,2,6,21105,5.0,120298.50,Anu
4,1005,2025-11-06,Mobile,Electronics,Bangalore,2,2,38526,10.0,69346.80,Anu
...,...,...,...,...,...,...,...,...,...,...,...
148,1149,2025-05-01,Laptop,Electronics,Kollam,2,4,74057,15.0,251793.80,Anu
149,1150,2025-04-08,Mouse,Accessories,Kollam,1,1,2130,10.0,1917.00,Arun
150,1011,2025-05-18,Laptop,Electronics,Trivandrum,1,1,65673,15.0,55822.05,Rahul
151,1036,2025-10-24,Headphones,Accessories,Bangalore,3,2,5666,5.0,10765.40,Anu
152,1081,2025-01-14,Mobile,Electronics,Kannur,2,5,22084,20.0,88336.00,Meera

In [40]:
 #! drop_duplicates()-> Is used to remove duplicate rows from a DataFrame.
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "A", "C"],
    "Age": [20, 21, 20, 22]})
df

  Name  Age
0    A   20
1    B   21
2    A   20
3    C   22

In [41]:
df = df.drop_duplicates()
df

  Name  Age
0    A   20
1    B   21
3    C   22

In [42]:
df.shape

(3, 2)

In [43]:
data = {
    "Name": ["Arun", "Anu", "Rahul", "Meera", "Adil"],
    "Mark1": [85, 78, 92, 75, 88],
    "Mark2": [90, 82, 88, 80, 95],
    "Gender": ["M", "F", "M", "F", "M"]
}

df=pd.DataFrame(data)
df

    Name  Mark1  Mark2 Gender
0   Arun     85     90      M
1    Anu     78     82      F
2  Rahul     92     88      M
3  Meera     75     80      F
4   Adil     88     95      M

In [44]:
 #! replace() -> Is used to replace specific values in a DataFrame or Series with new values.
df["Gender"]=df["Gender"].replace({"M":"Male","F":"Female"})
df

    Name  Mark1  Mark2  Gender
0   Arun     85     90    Male
1    Anu     78     82  Female
2  Rahul     92     88    Male
3  Meera     75     80  Female
4   Adil     88     95    Male

In [45]:
 #! astype() -> Changes datatype of a column
 #? int to float
df["Mark1"]=df["Mark1"].astype(float)
df

    Name  Mark1  Mark2  Gender
0   Arun   85.0     90    Male
1    Anu   78.0     82  Female
2  Rahul   92.0     88    Male
3  Meera   75.0     80  Female
4   Adil   88.0     95    Male

In [46]:
df["Mark1"]=df["Mark1"].astype(int)
df

    Name  Mark1  Mark2  Gender
0   Arun     85     90    Male
1    Anu     78     82  Female
2  Rahul     92     88    Male
3  Meera     75     80  Female
4   Adil     88     95    Male

In [47]:
df[["Mark1","Mark2"]]=df[["Mark1","Mark2"]].astype(float)
df

    Name  Mark1  Mark2  Gender
0   Arun   85.0   90.0    Male
1    Anu   78.0   82.0  Female
2  Rahul   92.0   88.0    Male
3  Meera   75.0   80.0  Female
4   Adil   88.0   95.0    Male

In [48]:
import pandas as pd
one = pd.DataFrame({'id':[101,102,103,104],'Name':['Ammu','Sneha', 'Rasina','sajad'],
                    'sub_id':['sub1','sub2','sub3','sub4'],'Mark':[23,25,24,27]},index=[1,2,3,4])
two = pd.DataFrame({'id':[101,102,103,104],'Name':['Ammu1','Sneha1' ,'Rasina1','sajad1'],
                    'sub_id':['sub1','sub2','sub3','sub4'],'Mark':[24,28,29,19]},index=[1,2,3,4])
three = pd.DataFrame({'Name':['Ammu2','Sneha2','Rasina2', 'sajad2'],
                      'sub_id':['sub1','sub2','sub3','sub4'],
                      'Mark':[18,12,15,19],'roll_no':[12,13,14,15]},index=[1,2,3,4])

In [49]:
pd.concat([one,two])

    id     Name sub_id  Mark
1  101     Ammu   sub1    23
2  102    Sneha   sub2    25
3  103   Rasina   sub3    24
4  104    sajad   sub4    27
1  101    Ammu1   sub1    24
2  102   Sneha1   sub2    28
3  103  Rasina1   sub3    29
4  104   sajad1   sub4    19

In [50]:
pd.concat([one,two,three])

      id     Name sub_id  Mark  roll_no
1  101.0     Ammu   sub1    23      NaN
2  102.0    Sneha   sub2    25      NaN
3  103.0   Rasina   sub3    24      NaN
4  104.0    sajad   sub4    27      NaN
1  101.0    Ammu1   sub1    24      NaN
2  102.0   Sneha1   sub2    28      NaN
3  103.0  Rasina1   sub3    29      NaN
4  104.0   sajad1   sub4    19      NaN
1    NaN    Ammu2   sub1    18     12.0
2    NaN   Sneha2   sub2    12     13.0
3    NaN  Rasina2   sub3    15     14.0
4    NaN   sajad2   sub4    19     15.0

In [51]:
pd.concat([one,two,three],keys=("x","y","z"))

        id     Name sub_id  Mark  roll_no
x 1  101.0     Ammu   sub1    23      NaN
  2  102.0    Sneha   sub2    25      NaN
  3  103.0   Rasina   sub3    24      NaN
  4  104.0    sajad   sub4    27      NaN
y 1  101.0    Ammu1   sub1    24      NaN
  2  102.0   Sneha1   sub2    28      NaN
  3  103.0  Rasina1   sub3    29      NaN
  4  104.0   sajad1   sub4    19      NaN
z 1    NaN    Ammu2   sub1    18     12.0
  2    NaN   Sneha2   sub2    12     13.0
  3    NaN  Rasina2   sub3    15     14.0
  4    NaN   sajad2   sub4    19     15.0

In [52]:
 #! ignore_index=True → resets the index numbers after combining
pd.concat([two,three],ignore_index=True)

      id     Name sub_id  Mark  roll_no
0  101.0    Ammu1   sub1    24      NaN
1  102.0   Sneha1   sub2    28      NaN
2  103.0  Rasina1   sub3    29      NaN
3  104.0   sajad1   sub4    19      NaN
4    NaN    Ammu2   sub1    18     12.0
5    NaN   Sneha2   sub2    12     13.0
6    NaN  Rasina2   sub3    15     14.0
7    NaN   sajad2   sub4    19     15.0

In [53]:
pd.concat([one,three],axis=1)   # concatenating column wise

    id    Name sub_id  Mark     Name sub_id  Mark  roll_no
1  101    Ammu   sub1    23    Ammu2   sub1    18       12
2  102   Sneha   sub2    25   Sneha2   sub2    12       13
3  103  Rasina   sub3    24  Rasina2   sub3    15       14
4  104   sajad   sub4    27   sajad2   sub4    19       15

In [54]:
pd.merge(one,two,on=["id","sub_id"])
#! Means: Match a row only when both id AND sub_id are the same in both DataFrames.

    id  Name_x sub_id  Mark_x   Name_y  Mark_y
0  101    Ammu   sub1      23    Ammu1      24
1  102   Sneha   sub2      25   Sneha1      28
2  103  Rasina   sub3      24  Rasina1      29
3  104   sajad   sub4      27   sajad1      19

In [55]:
pd.merge(one,two,on=["sub_id"])

   id_x  Name_x sub_id  Mark_x  id_y   Name_y  Mark_y
0   101    Ammu   sub1      23   101    Ammu1      24
1   102   Sneha   sub2      25   102   Sneha1      28
2   103  Rasina   sub3      24   103  Rasina1      29
3   104   sajad   sub4      27   104   sajad1      19

In [56]:
 #! how ->types of join:left,right,outer,inner
pd.merge(one,two,on="sub_id",how="left")
#! Means Combine one and two using sub_id as the matching column, while keeping ALL rows from one.

   id_x  Name_x sub_id  Mark_x  id_y   Name_y  Mark_y
0   101    Ammu   sub1      23   101    Ammu1      24
1   102   Sneha   sub2      25   102   Sneha1      28
2   103  Rasina   sub3      24   103  Rasina1      29
3   104   sajad   sub4      27   104   sajad1      19